# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_assignment1.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1241, 817)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.group_CIM = QtWidgets.QGroupBox(self.centralwidget)
        self.group_CIM.setGeometry(QtCore.QRect(20, 10, 391, 761))
        self.group_CIM.setObjectName("group_CIM")
        self.btn_browse_EQ = QtWidgets.QPushButton(self.group_CIM)
        self.btn_browse_EQ.setGeometry(QtCore.QRect(20, 20, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_browse_EQ.setFont(font)
        self.btn_browse_EQ.setObjectName("btn_browse_EQ")
        self.btn_browse_SSH = QtWidgets.QPushButton(self.group_CIM)
        self.btn_browse_SSH.setGeometry(QtCore.QRect(200, 20, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_browse_SSH.setFont(font)
        self.btn_browse_SSH.setObjectName("btn_browse_SSH")
        self.btn_parse_xml = QtWidgets.QPushButton(self.group_CIM)
        self.btn_parse_xml.setGeometry(QtCore.QRect(20, 70, 351, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_parse_xml.setFont(font)
        self.btn_parse_xml.setObjectName("btn_parse_xml")
        self.tree_xml = QtWidgets.QTreeView(self.group_CIM)
        self.tree_xml.setGeometry(QtCore.QRect(20, 230, 351, 511))
        self.tree_xml.setObjectName("tree_xml")
        self.edt_eq_path = QtWidgets.QLineEdit(self.group_CIM)
        self.edt_eq_path.setGeometry(QtCore.QRect(60, 170, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.edt_eq_path.setFont(font)
        self.edt_eq_path.setText("")
        self.edt_eq_path.setObjectName("edt_eq_path")
        self.edt_ssh_path = QtWidgets.QLineEdit(self.group_CIM)
        self.edt_ssh_path.setGeometry(QtCore.QRect(60, 200, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.edt_ssh_path.setFont(font)
        self.edt_ssh_path.setObjectName("edt_ssh_path")
        self.label_2 = QtWidgets.QLabel(self.group_CIM)
        self.label_2.setGeometry(QtCore.QRect(20, 170, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.group_CIM)
        self.label_3.setGeometry(QtCore.QRect(20, 200, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.group_SQL = QtWidgets.QGroupBox(self.centralwidget)
        self.group_SQL.setGeometry(QtCore.QRect(430, 10, 791, 191))
        self.group_SQL.setObjectName("group_SQL")
        self.btn_create_db = QtWidgets.QPushButton(self.group_SQL)
        self.btn_create_db.setGeometry(QtCore.QRect(420, 20, 351, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_create_db.setFont(font)
        self.btn_create_db.setObjectName("btn_create_db")
        self.edt_db_name = QtWidgets.QLineEdit(self.group_SQL)
        self.edt_db_name.setGeometry(QtCore.QRect(142, 45, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.edt_db_name.setFont(font)
        self.edt_db_name.setObjectName("edt_db_name")
        self.label = QtWidgets.QLabel(self.group_SQL)
        self.label.setGeometry(QtCore.QRect(20, 50, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.prog_SQL_db = QtWidgets.QProgressBar(self.group_SQL)
        self.prog_SQL_db.setEnabled(False)
        self.prog_SQL_db.setGeometry(QtCore.QRect(20, 140, 751, 23))
        self.prog_SQL_db.setProperty("value", 0)
        self.prog_SQL_db.setTextVisible(True)
        self.prog_SQL_db.setOrientation(QtCore.Qt.Horizontal)
        self.prog_SQL_db.setInvertedAppearance(False)
        self.prog_SQL_db.setObjectName("prog_SQL_db")
        self.group_adm_matrix = QtWidgets.QGroupBox(self.centralwidget)
        self.group_adm_matrix.setGeometry(QtCore.QRect(430, 210, 791, 561))
        self.group_adm_matrix.setObjectName("group_adm_matrix")
        self.btn_calc_Y_bus = QtWidgets.QPushButton(self.group_adm_matrix)
        self.btn_calc_Y_bus.setGeometry(QtCore.QRect(20, 20, 591, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_calc_Y_bus.setFont(font)
        self.btn_calc_Y_bus.setObjectName("btn_calc_Y_bus")
        self.tbl_Y_bus = QtWidgets.QTableWidget(self.group_adm_matrix)
        self.tbl_Y_bus.setGeometry(QtCore.QRect(20, 110, 751, 431))
        self.tbl_Y_bus.setObjectName("tbl_Y_bus")
        self.tbl_Y_bus.setColumnCount(0)
        self.tbl_Y_bus.setRowCount(0)
        self.tbl_Y_bus.horizontalHeader().setVisible(True)
        self.tbl_Y_bus.horizontalHeader().setDefaultSectionSize(80)
        self.tbl_Y_bus.verticalHeader().setVisible(True)
        self.tbl_Y_bus.verticalHeader().setDefaultSectionSize(20)
        self.btn_export_csv = QtWidgets.QPushButton(self.group_adm_matrix)
        self.btn_export_csv.setGeometry(QtCore.QRect(620, 20, 151, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_export_csv.setFont(font)
        self.btn_export_csv.setObjectName("btn_export_csv")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1241, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.group_CIM.setTitle(_translate("MainWindow", "CIM model files"))
        self.btn_browse_EQ.setText(_translate("MainWindow", "Browse EQ File"))
        self.btn_browse_SSH.setText(_translate("MainWindow", "Browse SSH File"))
        self.btn_parse_xml.setText(_translate("MainWindow", "Parse XML Files"))
        self.label_2.setText(_translate("MainWindow", "EQ:"))
        self.label_3.setText(_translate("MainWindow", "SSH:"))
        self.group_SQL.setTitle(_translate("MainWindow", "SQL Database"))
        self.btn_create_db.setText(_translate("MainWindow", "Store Data in SQL Database"))
        self.label.setText(_translate("MainWindow", "Database Name:"))
        self.group_adm_matrix.setTitle(_translate("MainWindow", "Admittance Matrix"))
        self.btn_calc_Y_bus.setText(_translate("MainWindow", "Calculate Admittance Matrix"))
        self.btn_export_csv.setText(_translate("MainWindow", "Export to CSV File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

